language: mega

sudo: required
dist: trusty

branches:
  only:
    - master

os:
  - linux
  #- osx

install:
  - if [ $TRAVIS_OS_NAME  == "linux" ]; then sudo apt-get install -y cmake libboost-all-dev python python-numpy liblua5.1-dev default-jdk zlib1g-dev libsdl2-dev libjpeg-dev nasm tar libbz2-dev libgtk2.0-dev libfluidsynth-dev libgme-dev libopenal-dev timidity; fi
  #- if ["$TRAVIS_OS_NAME" == "osx"]; then ...; fi

script:
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON=ON -DBUILD_LUA=ON -DBUILD_JAVA=ON
  - make